import { Inject, Injectable, Logger } from "@nestjs/common";
import { ConfigService } from "@nestjs/config";
import OpenAI from "openai";
import { pickBankQuestion } from "./question-bank";
import type { MirrorEntry } from "./mirror.repository";

const LLM_TIMEOUT_MS = 8000;
const MAX_QUESTION_LEN = 40;

export interface GeneratedQuestion {
  question: string;
  source: "llm" | "bank";
}

export type FallbackReason = "no_history" | "not_configured" | "llm_error" | "invalid_output";

/**
 * 每日镜子问题生成器：LLM 个性化 + 问题库兜底（design.md §2）。
 *
 * ⚠️ 临时散装 LLM 出口（design.md §3 收口约定）：
 * 本类直接调方舟 SDK，未经导师人格层。ai-mentor-core 落地统一导师上下文后，
 * 问题生成必须改为经导师人格发出（prompt 由 mentor 模块供给），届时删除本类的 LLM 调用。
 */
@Injectable()
export class QuestionGenerator {
  private readonly logger = new Logger(QuestionGenerator.name);

  constructor(@Inject(ConfigService) private readonly config: ConfigService) {}

  async generate(entryDate: string, recentAnswers: MirrorEntry[]): Promise<GeneratedQuestion> {
    if (recentAnswers.length === 0) {
      return this.bank(entryDate, "no_history");
    }

    const apiKey = this.config.get<string>("ARK_API_KEY");
    const model = this.config.get<string>("ARK_MODEL_ID");
    if (!apiKey || !model) {
      return this.bank(entryDate, "not_configured");
    }

    const startedAt = Date.now();
    try {
      const client = new OpenAI({
        apiKey,
        baseURL: this.config.get<string>(
          "ARK_BASE_URL",
          "https://ark.cn-beijing.volces.com/api/v3",
        ),
        timeout: LLM_TIMEOUT_MS,
        maxRetries: 0,
      });
      const completion = await client.chat.completions.create({
        model,
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: buildUserPrompt(recentAnswers) },
        ],
        // glm 推理模型：不显式关思考会耗尽 max_tokens 输出空 content（finish_reason=length）。
        // 一句问句不需要长思考；thinking 是方舟扩展字段，SDK 类型无定义，用展开绕过多余属性检查。
        max_tokens: 800,
        ...({ thinking: { type: "disabled" } } as object),
      });
      const raw = completion.choices[0]?.message?.content ?? "";
      const question = validateQuestion(raw);
      if (!question) {
        return this.bank(entryDate, "invalid_output", Date.now() - startedAt);
      }
      this.logger.log(`question generated by llm (${Date.now() - startedAt}ms)`);
      return { question, source: "llm" };
    } catch (err) {
      // 只记错误类别与耗时；不记请求/响应内容（含用户回答）
      this.logger.warn(
        `question llm failed: ${(err as Error).name} (${Date.now() - startedAt}ms)`,
      );
      return this.bank(entryDate, "llm_error", Date.now() - startedAt);
    }
  }

  private bank(entryDate: string, reason: FallbackReason, llmMs?: number): GeneratedQuestion {
    if (reason !== "no_history") {
      this.logger.warn(
        `question fallback to bank: ${reason}${llmMs !== undefined ? ` (${llmMs}ms)` : ""}`,
      );
    }
    return { question: pickBankQuestion(entryDate), source: "bank" };
  }
}

const SYSTEM_PROMPT = `你是一位温和的自我认知教练，每天给用户提一个反思问题。
要求：
- 只输出一句问句，不超过 40 字
- 温和、不评判、不说教
- 可以轻轻呼应用户最近提到的具体事，但不要复述隐私细节
- 不要输出任何解释、前缀或引号`;

/** 历史回答拼入 prompt（近 7 天已由 repository 限定）；日志不落此内容 */
function buildUserPrompt(recentAnswers: MirrorEntry[]): string {
  const lines = recentAnswers.map(
    (e) => `- ${e.entryDate} 问：${e.question}\n  答：${e.answer ?? ""}`,
  );
  return `这是用户最近几天的镜子回答：\n${lines.join("\n")}\n请生成今天的镜子问题。`;
}

/**
 * 输出校验：≤40 字、单行、以问号结尾。
 * 不合格按 LLM 失败处理（落问题库兜底）。
 */
export function validateQuestion(raw: string): string | null {
  const q = raw.trim().replace(/^[「"']+|[」"']+$/g, "").trim();
  if (q.length === 0 || q.length > MAX_QUESTION_LEN) return null;
  if (q.includes("\n")) return null;
  if (!q.endsWith("？") && !q.endsWith("?")) return null;
  return q;
}
